//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATP.SvcsLibrary.ErrorLogSvcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.AdamKiosks.com/Service/ErrorLog", ConfigurationName="ErrorLogSvcRef.IErrorLog")]
    public interface IErrorLog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AdamKiosks.com/Service/ErrorLog/IErrorLog/LogError", ReplyAction="http://www.AdamKiosks.com/Service/ErrorLog/IErrorLog/LogErrorResponse")]
        bool LogError(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AdamKiosks.com/Service/ErrorLog/IErrorLog/LogError", ReplyAction="http://www.AdamKiosks.com/Service/ErrorLog/IErrorLog/LogErrorResponse")]
        System.Threading.Tasks.Task<bool> LogErrorAsync(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AdamKiosks.com/Service/ErrorLog/IErrorLog/LogInformation", ReplyAction="http://www.AdamKiosks.com/Service/ErrorLog/IErrorLog/LogInformationResponse")]
        bool LogInformation(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AdamKiosks.com/Service/ErrorLog/IErrorLog/LogInformation", ReplyAction="http://www.AdamKiosks.com/Service/ErrorLog/IErrorLog/LogInformationResponse")]
        System.Threading.Tasks.Task<bool> LogInformationAsync(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IErrorLogChannel : ATP.SvcsLibrary.ErrorLogSvcRef.IErrorLog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErrorLogClient : System.ServiceModel.ClientBase<ATP.SvcsLibrary.ErrorLogSvcRef.IErrorLog>, ATP.SvcsLibrary.ErrorLogSvcRef.IErrorLog {
        
        public ErrorLogClient() {
        }
        
        public ErrorLogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErrorLogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorLogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LogError(string msg) {
            return base.Channel.LogError(msg);
        }
        
        public System.Threading.Tasks.Task<bool> LogErrorAsync(string msg) {
            return base.Channel.LogErrorAsync(msg);
        }
        
        public bool LogInformation(string msg) {
            return base.Channel.LogInformation(msg);
        }
        
        public System.Threading.Tasks.Task<bool> LogInformationAsync(string msg) {
            return base.Channel.LogInformationAsync(msg);
        }
    }
}
