#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyShopWeb.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_9F2CA9_MyShopAuto")]
	public partial class MyShopDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MyShopDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_9F2CA9_MyShopAutoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MyShopDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyShopDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyShopDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MyShopDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelAllStickerStatus")]
		public ISingleResult<uspSelAllStickerStatusResult> uspSelAllStickerStatus()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspSelAllStickerStatusResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelAllStickerTypes")]
		public ISingleResult<uspSelAllStickerTypesResult> uspSelAllStickerTypes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspSelAllStickerTypesResult>)(result.ReturnValue));
		}
	}
	
	public partial class uspSelAllStickerStatusResult
	{
		
		private byte _StickerStatusId;
		
		private string _StickerIssuedStatus;
		
		public uspSelAllStickerStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StickerStatusId", DbType="TinyInt NOT NULL")]
		public byte StickerStatusId
		{
			get
			{
				return this._StickerStatusId;
			}
			set
			{
				if ((this._StickerStatusId != value))
				{
					this._StickerStatusId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StickerIssuedStatus", DbType="VarChar(100)")]
		public string StickerIssuedStatus
		{
			get
			{
				return this._StickerIssuedStatus;
			}
			set
			{
				if ((this._StickerIssuedStatus != value))
				{
					this._StickerIssuedStatus = value;
				}
			}
		}
	}
	
	public partial class uspSelAllStickerTypesResult
	{
		
		private byte _StickerTypeId;
		
		private string _StickerTypeCD;
		
		private string _StickerType;
		
		private string _StickerDesc;
		
		public uspSelAllStickerTypesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StickerTypeId", DbType="TinyInt NOT NULL")]
		public byte StickerTypeId
		{
			get
			{
				return this._StickerTypeId;
			}
			set
			{
				if ((this._StickerTypeId != value))
				{
					this._StickerTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StickerTypeCD", DbType="VarChar(10)")]
		public string StickerTypeCD
		{
			get
			{
				return this._StickerTypeCD;
			}
			set
			{
				if ((this._StickerTypeCD != value))
				{
					this._StickerTypeCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StickerType", DbType="VarChar(100)")]
		public string StickerType
		{
			get
			{
				return this._StickerType;
			}
			set
			{
				if ((this._StickerType != value))
				{
					this._StickerType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StickerDesc", DbType="VarChar(100)")]
		public string StickerDesc
		{
			get
			{
				return this._StickerDesc;
			}
			set
			{
				if ((this._StickerDesc != value))
				{
					this._StickerDesc = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
